// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3gaioRNCj0GYU1icAeDQR-pqjB3a0MWo',
    appId: '1:118962585884:web:a9441bc9d24e45bf6fbad9',
    messagingSenderId: '118962585884',
    projectId: 'prepa-spotify',
    authDomain: 'prepa-spotify.firebaseapp.com',
    storageBucket: 'prepa-spotify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvb5sD9L6fT7J7MH6m1nN9sXekWt36VhE',
    appId: '1:118962585884:android:7a53f43856cb9aa46fbad9',
    messagingSenderId: '118962585884',
    projectId: 'prepa-spotify',
    storageBucket: 'prepa-spotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOXUjozE2Sx3I2y6iaHy9wthOWbc-a0xU',
    appId: '1:118962585884:ios:afddc08b319ab58c6fbad9',
    messagingSenderId: '118962585884',
    projectId: 'prepa-spotify',
    storageBucket: 'prepa-spotify.firebasestorage.app',
    iosBundleId: 'com.example.spotifyPrepa',
  );
}
